# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
resources:
  repositories:
    - repository: crux
      type: github
      name: ObjectivityLtd/crux
      #ref: refs/heads/feature/junit_percentile_thresholds
      endpoint: crux

    - repository: tests
      type: github
      name: ObjectivityLtd/jmeter_simple_test
      endpoint: crux


parameters:
  - name: debug
    type: boolean
    default: false

  - name: mode
    default: jmeter
    values:
      - tests
      - jmeter
  - name: data_file
    type: string
    default: path/to/jmeter/test_data/sample_data.csv
    values:
      - path/to/jmeter/test_data/sample_data.csv

  - name: jmeter_slaves
    default: 1
    type: number

  - name: jmx
    default: path/to/jmeter/script/bing.jmx
    type: string

  - name: jmeter_args
    default: "-Gthreads=1 -Gloops=1"
    type: string

  - name: connection
    default: k8con2
    type: string

variables:
  cluster_namespace: default
  kubernetesServiceConnection: ${{ parameters.connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  data_file: $(repoName)/${{ parameters.data_file }}
  jmeter_args: ${{ parameters.jmeter_args }}
  repoName: jmeter_simple_test
  cruxRepoName: crux
  scenario: $(repoName)/${{ parameters.jmx }}

jobs:
  - template: templates/run.mode.selector.yaml
    parameters:
      mode: ${{ parameters.mode }}
      debug: ${{ parameters.debug }}