# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
parameters:
  - name: debug
    default: false

- name: mode
  default: jmeter
  values:
    - tests
    - jmeter
- name: data_file
  default: test_data/sample_data.csv
  values:
    - test_data/sample_data.csv
    - test_data/sample_data2.csv
- name: jmeter_slaves
  default: 3
  type: number

- name: repo_name
  default: jmeter_simple_test
  type: string

- name: jmeter_args
  default: "-Gthreads=1 -Gloops=1"
  type: string

- name: connection
  default: k8con2
  type: string

variables:
  cluster_namespace: default
  kubernetesServiceConnection: ${{ parameters.connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  data_file: ${{ parameters.data_file }}
  jmeter_args: ${{ parameters.jmeter_args }}
  repoName: ${{ parameters.repo_name }}
  user: user
  pass: pass
  repoBaseURL: https://$(user):$(pass)@github.com/ObjectivityLtd
  repoURL: $(repoBaseURL)/$(repoName)
  scenario: $(repoName)/path/to/jmeter/script/test.jmx

jobs:
  - template: templates/run.mode.selector.yaml
    parameters:
      mode: ${{ parameters.mode }}